// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/updater/updater.proto

package hanako_srv_updater

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Updater service

type UpdaterService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Updater_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Updater_PingPongService, error)
}

type updaterService struct {
	c    client.Client
	name string
}

func NewUpdaterService(name string, c client.Client) UpdaterService {
	return &updaterService{
		c:    c,
		name: name,
	}
}

func (c *updaterService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Updater.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updaterService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Updater_StreamService, error) {
	req := c.c.NewRequest(c.name, "Updater.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &updaterServiceStream{stream}, nil
}

type Updater_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type updaterServiceStream struct {
	stream client.Stream
}

func (x *updaterServiceStream) Close() error {
	return x.stream.Close()
}

func (x *updaterServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *updaterServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *updaterServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *updaterServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *updaterService) PingPong(ctx context.Context, opts ...client.CallOption) (Updater_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Updater.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &updaterServicePingPong{stream}, nil
}

type Updater_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type updaterServicePingPong struct {
	stream client.Stream
}

func (x *updaterServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *updaterServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *updaterServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *updaterServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *updaterServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *updaterServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Updater service

type UpdaterHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Updater_StreamStream) error
	PingPong(context.Context, Updater_PingPongStream) error
}

func RegisterUpdaterHandler(s server.Server, hdlr UpdaterHandler, opts ...server.HandlerOption) error {
	type updater interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Updater struct {
		updater
	}
	h := &updaterHandler{hdlr}
	return s.Handle(s.NewHandler(&Updater{h}, opts...))
}

type updaterHandler struct {
	UpdaterHandler
}

func (h *updaterHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.UpdaterHandler.Call(ctx, in, out)
}

func (h *updaterHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.UpdaterHandler.Stream(ctx, m, &updaterStreamStream{stream})
}

type Updater_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type updaterStreamStream struct {
	stream server.Stream
}

func (x *updaterStreamStream) Close() error {
	return x.stream.Close()
}

func (x *updaterStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *updaterStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *updaterStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *updaterStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *updaterHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.UpdaterHandler.PingPong(ctx, &updaterPingPongStream{stream})
}

type Updater_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type updaterPingPongStream struct {
	stream server.Stream
}

func (x *updaterPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *updaterPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *updaterPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *updaterPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *updaterPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *updaterPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
