// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/search/proto/anime.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8acf4828c97bfe95, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type Request struct {
	AnimeId              int32    `protobuf:"varint,1,opt,name=animeId,proto3" json:"animeId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8acf4828c97bfe95, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAnimeId() int32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

func (m *Request) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Results struct {
	Animes               []*Anime `protobuf:"bytes,1,rep,name=animes,proto3" json:"animes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Results) Reset()         { *m = Results{} }
func (m *Results) String() string { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()    {}
func (*Results) Descriptor() ([]byte, []int) {
	return fileDescriptor_8acf4828c97bfe95, []int{2}
}

func (m *Results) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Results.Unmarshal(m, b)
}
func (m *Results) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Results.Marshal(b, m, deterministic)
}
func (m *Results) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Results.Merge(m, src)
}
func (m *Results) XXX_Size() int {
	return xxx_messageInfo_Results.Size(m)
}
func (m *Results) XXX_DiscardUnknown() {
	xxx_messageInfo_Results.DiscardUnknown(m)
}

var xxx_messageInfo_Results proto.InternalMessageInfo

func (m *Results) GetAnimes() []*Anime {
	if m != nil {
		return m.Animes
	}
	return nil
}

type Anime struct {
	Sources              []string `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Episodes             int32    `protobuf:"varint,4,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Picture              string   `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	Thumbnail            string   `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Synonyms             []string `protobuf:"bytes,8,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Relations            []string `protobuf:"bytes,9,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime) Reset()         { *m = Anime{} }
func (m *Anime) String() string { return proto.CompactTextString(m) }
func (*Anime) ProtoMessage()    {}
func (*Anime) Descriptor() ([]byte, []int) {
	return fileDescriptor_8acf4828c97bfe95, []int{3}
}

func (m *Anime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime.Unmarshal(m, b)
}
func (m *Anime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime.Marshal(b, m, deterministic)
}
func (m *Anime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime.Merge(m, src)
}
func (m *Anime) XXX_Size() int {
	return xxx_messageInfo_Anime.Size(m)
}
func (m *Anime) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime.DiscardUnknown(m)
}

var xxx_messageInfo_Anime proto.InternalMessageInfo

func (m *Anime) GetSources() []string {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Anime) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Anime) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Anime) GetEpisodes() int32 {
	if m != nil {
		return m.Episodes
	}
	return 0
}

func (m *Anime) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Anime) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Anime) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Anime) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *Anime) GetRelations() []string {
	if m != nil {
		return m.Relations
	}
	return nil
}

func init() {
	proto.RegisterType((*Nothing)(nil), "search.Nothing")
	proto.RegisterType((*Request)(nil), "search.Request")
	proto.RegisterType((*Results)(nil), "search.Results")
	proto.RegisterType((*Anime)(nil), "search.Anime")
}

func init() { proto.RegisterFile("services/search/proto/anime.proto", fileDescriptor_8acf4828c97bfe95) }

var fileDescriptor_8acf4828c97bfe95 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0xb6, 0xd9, 0x34, 0x23, 0x22, 0x2c, 0x22, 0x4b, 0xf1, 0x50, 0x03, 0x42, 0xe9, 0xa1,
	0x95, 0xfa, 0x05, 0xf5, 0x22, 0x5e, 0x3c, 0xc4, 0x1f, 0x30, 0x4d, 0x07, 0xbb, 0x90, 0x66, 0x63,
	0x66, 0x22, 0xe4, 0xb3, 0xfd, 0x03, 0xd9, 0x49, 0xd2, 0xd6, 0xa3, 0xb7, 0x79, 0xef, 0xcd, 0xec,
	0x3c, 0xde, 0x2c, 0xdc, 0x13, 0xd6, 0xdf, 0x36, 0x47, 0x5a, 0x11, 0x66, 0x75, 0xbe, 0x5f, 0x55,
	0xb5, 0x63, 0xb7, 0xca, 0x4a, 0x7b, 0xc0, 0xa5, 0xd4, 0x5a, 0x75, 0x4a, 0x12, 0x43, 0xf4, 0xe6,
	0x78, 0x6f, 0xcb, 0xcf, 0x04, 0x21, 0x4a, 0xf1, 0xab, 0x41, 0x62, 0x6d, 0x20, 0x92, 0xe6, 0xd7,
	0x9d, 0x09, 0x66, 0xc1, 0x3c, 0x4c, 0x07, 0xa8, 0x6f, 0x20, 0x64, 0xcb, 0x05, 0x9a, 0x8b, 0x59,
	0x30, 0x8f, 0xd3, 0x0e, 0x68, 0x0d, 0x63, 0x6e, 0x2b, 0x34, 0x23, 0x21, 0xa5, 0xd6, 0xb7, 0xa0,
	0x88, 0x33, 0x6e, 0xc8, 0x8c, 0x85, 0xed, 0x51, 0xf2, 0xe8, 0xd7, 0x50, 0x53, 0x30, 0xe9, 0x07,
	0x50, 0xf2, 0x2e, 0x99, 0x60, 0x36, 0x9a, 0x5f, 0xae, 0xaf, 0x96, 0x9d, 0xab, 0xe5, 0xc6, 0xb3,
	0x69, 0x2f, 0x26, 0x3f, 0x01, 0x84, 0xc2, 0x78, 0x5f, 0xe4, 0x9a, 0x3a, 0xef, 0x27, 0xe2, 0x74,
	0x80, 0xff, 0xf0, 0x35, 0x85, 0x09, 0x56, 0x96, 0xdc, 0x0e, 0x3b, 0x67, 0x61, 0x7a, 0xc4, 0x67,
	0x9e, 0xc3, 0x73, 0xcf, 0x7e, 0x6f, 0x65, 0x73, 0x6e, 0x6a, 0x34, 0x4a, 0x84, 0x01, 0xea, 0x3b,
	0x88, 0x79, 0xdf, 0x1c, 0xb6, 0x65, 0x66, 0x0b, 0x13, 0x89, 0x76, 0x22, 0xfc, 0x2e, 0x6a, 0x4b,
	0x57, 0xb6, 0x07, 0x32, 0x13, 0x31, 0x7c, 0xc4, 0x7e, 0xb2, 0xc6, 0x22, 0x63, 0xeb, 0x4a, 0x32,
	0xb1, 0x88, 0x27, 0x62, 0xfd, 0x01, 0xea, 0x5d, 0xb2, 0xd0, 0x0b, 0x98, 0x74, 0xd5, 0x73, 0xab,
	0xaf, 0x87, 0x80, 0xfa, 0x43, 0x4d, 0xff, 0x26, 0xa6, 0x17, 0xa0, 0x5e, 0x90, 0x37, 0x45, 0x71,
	0xea, 0xec, 0xaf, 0x3b, 0x3d, 0x1b, 0x95, 0xf0, 0xb7, 0x4a, 0x3e, 0xc2, 0xd3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x42, 0x58, 0x44, 0x2d, 0x02, 0x00, 0x00,
}
