// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: services/search/proto/anime.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Search service

type SearchService interface {
	SearchBy(ctx context.Context, in *Request, opts ...client.CallOption) (*Anime, error)
	GetAll(ctx context.Context, in *Nothing, opts ...client.CallOption) (*Results, error)
}

type searchService struct {
	c    client.Client
	name string
}

func NewSearchService(name string, c client.Client) SearchService {
	return &searchService{
		c:    c,
		name: name,
	}
}

func (c *searchService) SearchBy(ctx context.Context, in *Request, opts ...client.CallOption) (*Anime, error) {
	req := c.c.NewRequest(c.name, "Search.SearchBy", in)
	out := new(Anime)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchService) GetAll(ctx context.Context, in *Nothing, opts ...client.CallOption) (*Results, error) {
	req := c.c.NewRequest(c.name, "Search.GetAll", in)
	out := new(Results)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Search service

type SearchHandler interface {
	SearchBy(context.Context, *Request, *Anime) error
	GetAll(context.Context, *Nothing, *Results) error
}

func RegisterSearchHandler(s server.Server, hdlr SearchHandler, opts ...server.HandlerOption) error {
	type search interface {
		SearchBy(ctx context.Context, in *Request, out *Anime) error
		GetAll(ctx context.Context, in *Nothing, out *Results) error
	}
	type Search struct {
		search
	}
	h := &searchHandler{hdlr}
	return s.Handle(s.NewHandler(&Search{h}, opts...))
}

type searchHandler struct {
	SearchHandler
}

func (h *searchHandler) SearchBy(ctx context.Context, in *Request, out *Anime) error {
	return h.SearchHandler.SearchBy(ctx, in, out)
}

func (h *searchHandler) GetAll(ctx context.Context, in *Nothing, out *Results) error {
	return h.SearchHandler.GetAll(ctx, in, out)
}
