// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/anime/anime.proto

package hanako_srv_anime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParam) Reset()         { *m = NoParam{} }
func (m *NoParam) String() string { return proto.CompactTextString(m) }
func (*NoParam) ProtoMessage()    {}
func (*NoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c518ae8dab0f146, []int{0}
}

func (m *NoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParam.Unmarshal(m, b)
}
func (m *NoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParam.Marshal(b, m, deterministic)
}
func (m *NoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParam.Merge(m, src)
}
func (m *NoParam) XXX_Size() int {
	return xxx_messageInfo_NoParam.Size(m)
}
func (m *NoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParam.DiscardUnknown(m)
}

var xxx_messageInfo_NoParam proto.InternalMessageInfo

type Anime struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Sources              []string `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Episodes             int32    `protobuf:"varint,5,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Picture              string   `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	Thumbnail            string   `protobuf:"bytes,8,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Synonyms             []string `protobuf:"bytes,9,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Relations            []string `protobuf:"bytes,10,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime) Reset()         { *m = Anime{} }
func (m *Anime) String() string { return proto.CompactTextString(m) }
func (*Anime) ProtoMessage()    {}
func (*Anime) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c518ae8dab0f146, []int{1}
}

func (m *Anime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime.Unmarshal(m, b)
}
func (m *Anime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime.Marshal(b, m, deterministic)
}
func (m *Anime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime.Merge(m, src)
}
func (m *Anime) XXX_Size() int {
	return xxx_messageInfo_Anime.Size(m)
}
func (m *Anime) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime.DiscardUnknown(m)
}

var xxx_messageInfo_Anime proto.InternalMessageInfo

func (m *Anime) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Anime) GetSources() []string {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Anime) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Anime) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Anime) GetEpisodes() int32 {
	if m != nil {
		return m.Episodes
	}
	return 0
}

func (m *Anime) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Anime) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Anime) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Anime) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *Anime) GetRelations() []string {
	if m != nil {
		return m.Relations
	}
	return nil
}

type Request struct {
	AnimeId              []string `protobuf:"bytes,1,rep,name=animeId,proto3" json:"animeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c518ae8dab0f146, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAnimeId() []string {
	if m != nil {
		return m.AnimeId
	}
	return nil
}

type Results struct {
	Animes               []*Anime `protobuf:"bytes,1,rep,name=animes,proto3" json:"animes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Results) Reset()         { *m = Results{} }
func (m *Results) String() string { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()    {}
func (*Results) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c518ae8dab0f146, []int{3}
}

func (m *Results) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Results.Unmarshal(m, b)
}
func (m *Results) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Results.Marshal(b, m, deterministic)
}
func (m *Results) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Results.Merge(m, src)
}
func (m *Results) XXX_Size() int {
	return xxx_messageInfo_Results.Size(m)
}
func (m *Results) XXX_DiscardUnknown() {
	xxx_messageInfo_Results.DiscardUnknown(m)
}

var xxx_messageInfo_Results proto.InternalMessageInfo

func (m *Results) GetAnimes() []*Anime {
	if m != nil {
		return m.Animes
	}
	return nil
}

func init() {
	proto.RegisterType((*NoParam)(nil), "hanako.srv.anime.NoParam")
	proto.RegisterType((*Anime)(nil), "hanako.srv.anime.Anime")
	proto.RegisterType((*Request)(nil), "hanako.srv.anime.Request")
	proto.RegisterType((*Results)(nil), "hanako.srv.anime.Results")
}

func init() { proto.RegisterFile("proto/anime/anime.proto", fileDescriptor_2c518ae8dab0f146) }

var fileDescriptor_2c518ae8dab0f146 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xa4, 0x4d, 0xd2, 0xcc, 0x2b, 0x22, 0x8b, 0xd8, 0xb5, 0x78, 0x28, 0xf1, 0xd2,
	0x53, 0x0a, 0xf5, 0xe6, 0x49, 0xf1, 0x20, 0xbd, 0x88, 0xc4, 0x4f, 0xb0, 0x6d, 0x07, 0xba, 0x98,
	0x64, 0xe3, 0xce, 0xa6, 0xd0, 0xa3, 0x1f, 0xc2, 0xef, 0x2b, 0x3b, 0x4d, 0x5b, 0xd0, 0xe2, 0x25,
	0xe4, 0xf9, 0xcd, 0xdf, 0x7d, 0x76, 0x61, 0xd8, 0x58, 0xe3, 0xcc, 0x54, 0xd5, 0xba, 0xc2, 0xdd,
	0x37, 0x67, 0x22, 0x2e, 0xd6, 0xaa, 0x56, 0xef, 0x26, 0x27, 0xbb, 0xc9, 0x99, 0x67, 0x29, 0x24,
	0x2f, 0xe6, 0x55, 0x59, 0x55, 0x65, 0x9f, 0x21, 0x44, 0x8f, 0x1e, 0x8a, 0x73, 0x08, 0xe7, 0x2b,
	0x19, 0x8c, 0x83, 0x49, 0x5a, 0x84, 0xf3, 0x95, 0x90, 0x90, 0x90, 0x69, 0xed, 0x12, 0x49, 0x86,
	0xe3, 0xde, 0x24, 0x2d, 0xf6, 0x52, 0x5c, 0x42, 0xe4, 0xb4, 0x2b, 0x51, 0xf6, 0x38, 0x79, 0x27,
	0x84, 0x80, 0xbe, 0xdb, 0x36, 0x28, 0xfb, 0x0c, 0xf9, 0x5f, 0x8c, 0x60, 0x80, 0x8d, 0x26, 0xb3,
	0x42, 0x92, 0xd1, 0x38, 0x98, 0x44, 0xc5, 0x41, 0x8b, 0x2b, 0x88, 0xc9, 0x29, 0xd7, 0x92, 0x8c,
	0xb9, 0xa2, 0x53, 0x7e, 0x6e, 0xa3, 0x97, 0xae, 0xb5, 0x28, 0x13, 0x0e, 0xec, 0xa5, 0xb8, 0x81,
	0xd4, 0xad, 0xdb, 0x6a, 0x51, 0x2b, 0x5d, 0xca, 0x01, 0xc7, 0x8e, 0xc0, 0xcf, 0xa2, 0x6d, 0x6d,
	0xea, 0x6d, 0x45, 0x32, 0xe5, 0x85, 0x0f, 0xda, 0x57, 0x5a, 0x2c, 0x95, 0xd3, 0xa6, 0x26, 0x09,
	0x1c, 0x3c, 0x82, 0xec, 0x16, 0x92, 0x02, 0x3f, 0x5a, 0x24, 0xe7, 0x87, 0xb3, 0x45, 0xec, 0x04,
	0x1f, 0xba, 0x93, 0xd9, 0xbd, 0x4f, 0xa2, 0xb6, 0x74, 0x24, 0xa6, 0x10, 0x33, 0x25, 0xce, 0xf9,
	0x3f, 0x1b, 0xe6, 0x3f, 0x1d, 0xce, 0xd9, 0xd2, 0xa2, 0x4b, 0x9b, 0x7d, 0x05, 0x70, 0xc6, 0xe4,
	0x0d, 0xed, 0x46, 0x2f, 0x51, 0x3c, 0x41, 0xfa, 0x8c, 0x8e, 0x11, 0x89, 0xeb, 0xdf, 0xe5, 0xdd,
	0x3a, 0xa3, 0x93, 0x21, 0x5e, 0x22, 0xfb, 0x27, 0x1e, 0x20, 0xf6, 0x4d, 0xca, 0xf2, 0x54, 0x87,
	0xee, 0x7e, 0xff, 0xec, 0xb0, 0x88, 0xf9, 0x81, 0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0x53, 0x39, 0x5a, 0x3b, 0x02, 0x00, 0x00,
}
