// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rest.proto

package rest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/micro/micro/api/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Rest service

type RestService interface {
	Search(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type restService struct {
	c    client.Client
	name string
}

func NewRestService(name string, c client.Client) RestService {
	return &restService{
		c:    c,
		name: name,
	}
}

func (c *restService) Search(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Rest.Search", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rest service

type RestHandler interface {
	Search(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterRestHandler(s server.Server, hdlr RestHandler, opts ...server.HandlerOption) error {
	type rest interface {
		Search(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Rest struct {
		rest
	}
	h := &restHandler{hdlr}
	return s.Handle(s.NewHandler(&Rest{h}, opts...))
}

type restHandler struct {
	RestHandler
}

func (h *restHandler) Search(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.RestHandler.Search(ctx, in, out)
}
