// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/anime.proto

package anime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AnimeService service

type AnimeService interface {
	GetAnimes(ctx context.Context, in *Request, opts ...client.CallOption) (*Results, error)
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Results, error)
}

type animeService struct {
	c    client.Client
	name string
}

func NewAnimeService(name string, c client.Client) AnimeService {
	return &animeService{
		c:    c,
		name: name,
	}
}

func (c *animeService) GetAnimes(ctx context.Context, in *Request, opts ...client.CallOption) (*Results, error) {
	req := c.c.NewRequest(c.name, "AnimeService.GetAnimes", in)
	out := new(Results)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animeService) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Results, error) {
	req := c.c.NewRequest(c.name, "AnimeService.GetAll", in)
	out := new(Results)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AnimeService service

type AnimeServiceHandler interface {
	GetAnimes(context.Context, *Request, *Results) error
	GetAll(context.Context, *Request, *Results) error
}

func RegisterAnimeServiceHandler(s server.Server, hdlr AnimeServiceHandler, opts ...server.HandlerOption) error {
	type animeService interface {
		GetAnimes(ctx context.Context, in *Request, out *Results) error
		GetAll(ctx context.Context, in *Request, out *Results) error
	}
	type AnimeService struct {
		animeService
	}
	h := &animeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AnimeService{h}, opts...))
}

type animeServiceHandler struct {
	AnimeServiceHandler
}

func (h *animeServiceHandler) GetAnimes(ctx context.Context, in *Request, out *Results) error {
	return h.AnimeServiceHandler.GetAnimes(ctx, in, out)
}

func (h *animeServiceHandler) GetAll(ctx context.Context, in *Request, out *Results) error {
	return h.AnimeServiceHandler.GetAll(ctx, in, out)
}
